export const INITIAL_VEHICLES = [
  {
    id: 1,
    make: 'Royal Enfield',
    model: 'Hunter 350 (Rapido Bike)',
    year: 2024,
    licensePlate: 'KA-05-BK-3344',
    category: 'BIKE',
    seats: 1,
    fuelType: 'Petrol (350cc)',
    transmission: 'Manual',
    pricePerKm: 7.0,
    baseFare: 25.0,
    hourlyRate: 80.0,
    rating: 4.95,
    totalTrips: 184,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800',
    features: 'Sanitized Helmet, Traffic Cutter, Fast Pickup, Luggage Hook',
    maxWeightKg: null,
  },
  {
    id: 2,
    make: 'Honda',
    model: 'Activa 6G (Rapido Bike)',
    year: 2024,
    licensePlate: 'KA-01-AC-9922',
    category: 'BIKE',
    seats: 1,
    fuelType: 'Petrol (110cc)',
    transmission: 'Automatic',
    pricePerKm: 6.0,
    baseFare: 20.0,
    hourlyRate: 70.0,
    rating: 4.9,
    totalTrips: 312,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800',
    features: 'Sanitized Helmet, Footboard Space, Smooth Ride, Economical',
    maxWeightKg: null,
  },
  {
    id: 3,
    make: 'Bajaj',
    model: 'RE Compact (CNG Auto)',
    year: 2023,
    licensePlate: 'KA-03-TR-8811',
    category: 'AUTO',
    seats: 3,
    fuelType: 'CNG Green',
    transmission: 'Manual',
    pricePerKm: 12.0,
    baseFare: 45.0,
    hourlyRate: 140.0,
    rating: 4.88,
    totalTrips: 420,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1596706037526-7f41df0bb2f5?w=800',
    features: '3 Passengers, Upfront Fixed Meter, Doorstep Pickup, Open Air',
    maxWeightKg: null,
  },
  {
    id: 4,
    make: 'Mahindra',
    model: 'Treo EV (Auto Rickshaw)',
    year: 2024,
    licensePlate: 'KA-04-EV-5566',
    category: 'AUTO',
    seats: 3,
    fuelType: 'Electric (Zero Emission)',
    transmission: 'Automatic',
    pricePerKm: 11.0,
    baseFare: 40.0,
    hourlyRate: 130.0,
    rating: 4.92,
    totalTrips: 215,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1558441719-5a8286a11e40?w=800',
    features: 'Zero Emission, Silent Drive, Digital Meter, Spacious Cabin',
    maxWeightKg: null,
  },
  {
    id: 5,
    make: 'Maruti Suzuki',
    model: 'Dzire Prime (Uber Sedan)',
    year: 2023,
    licensePlate: 'KA-05-DZ-1234',
    category: 'SEDAN',
    seats: 4,
    fuelType: 'Petrol / CNG',
    transmission: 'Manual',
    pricePerKm: 18.0,
    baseFare: 90.0,
    hourlyRate: 250.0,
    rating: 4.89,
    totalTrips: 540,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
    features: 'AC, Boot Space for 3 Bags, Fastag, Verified Chauffeur',
    maxWeightKg: null,
  },
  {
    id: 6,
    make: 'Tesla',
    model: 'Model 3 (Uber Green EV)',
    year: 2024,
    licensePlate: 'KA-01-TS-7788',
    category: 'ELECTRIC',
    seats: 4,
    fuelType: 'Electric (Long Range)',
    transmission: 'Automatic',
    pricePerKm: 35.0,
    baseFare: 150.0,
    hourlyRate: 500.0,
    rating: 4.98,
    totalTrips: 120,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    features: 'Silent Cabin, Autopilot Telemetry, Glass Roof, Premium Audio',
    maxWeightKg: null,
  },
  {
    id: 7,
    make: 'Hyundai',
    model: 'Creta (Uber Family SUV)',
    year: 2024,
    licensePlate: 'KA-51-CR-4433',
    category: 'SUV',
    seats: 6,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    pricePerKm: 24.0,
    baseFare: 120.0,
    hourlyRate: 380.0,
    rating: 4.91,
    totalTrips: 290,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
    features: 'Panoramic Sunroof, 6 Seater, Large Boot, Bose Speakers',
    maxWeightKg: null,
  },
  {
    id: 8,
    make: 'BMW',
    model: '530i M Sport (Uber Black)',
    year: 2024,
    licensePlate: 'KA-01-BM-9999',
    category: 'LUXURY',
    seats: 4,
    fuelType: 'Turbo Petrol',
    transmission: 'Automatic',
    pricePerKm: 48.0,
    baseFare: 250.0,
    hourlyRate: 850.0,
    rating: 4.99,
    totalTrips: 85,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    features: 'Executive Chauffeur, Leather Seats, Chilled Water, Ambient Light',
    maxWeightKg: null,
  },
  {
    id: 9,
    make: 'Tata',
    model: 'Ace Gold (Trolley / Porter)',
    year: 2023,
    licensePlate: 'KA-02-TC-7766',
    category: 'TROLLEY_PORTER',
    seats: 2,
    fuelType: 'Diesel BS6',
    transmission: 'Manual',
    pricePerKm: 25.0,
    baseFare: 180.0,
    hourlyRate: 350.0,
    rating: 4.87,
    totalTrips: 640,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800',
    features: 'Max 750 kg Payload, Tarpaulin Cover, Loading Assistance, Commercial Shifting',
    maxWeightKg: 750,
  },
  {
    id: 10,
    make: 'Piaggio',
    model: 'Ape Cargo (Trolley Loader)',
    year: 2023,
    licensePlate: 'KA-04-AP-1100',
    category: 'TROLLEY_PORTER',
    seats: 1,
    fuelType: 'CNG Cargo',
    transmission: 'Manual',
    pricePerKm: 20.0,
    baseFare: 140.0,
    hourlyRate: 260.0,
    rating: 4.84,
    totalTrips: 380,
    status: 'AVAILABLE',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    features: 'Max 400 kg Payload, Narrow Lane Delivery, Parcel Shifting, Quick Dispatch',
    maxWeightKg: 400,
  }
];

export const DEMO_USERS = {
  customer: {
    id: 1,
    fullName: 'Priya Sharma',
    email: 'customer@drivepulse.com',
    role: 'ROLE_CUSTOMER',
    phoneNumber: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  driver: {
    id: 2,
    fullName: 'Rajesh Kumar',
    email: 'driver@drivepulse.com',
    role: 'ROLE_DRIVER',
    phoneNumber: '+91 98765 12345',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    rating: 4.92,
    totalTrips: 582,
    vehicleAssigned: 'Royal Enfield Hunter 350 (KA-05-BK-3344)',
    isOnline: true,
  },
  admin: {
    id: 3,
    fullName: 'Platform Operations Admin',
    email: 'admin@drivepulse.com',
    role: 'ROLE_ADMIN',
    phoneNumber: '+91 98765 00000',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
  }
};

export const DEMO_DRIVERS = [
  {
    id: 1,
    user: DEMO_USERS.driver,
    licenseNumber: 'KA-05-2019-0038472',
    vehicleAssigned: 'Royal Enfield Hunter 350 (KA-05-BK-3344)',
    category: 'BIKE',
    experienceYears: 5,
    verificationStatus: 'APPROVED',
    rating: 4.92,
    totalTrips: 582,
    totalEarnings: 48520,
    completionRate: '99.2%',
    joinedDate: 'March 2022',
    reviews: [
      {
        id: 'rev-101',
        tripCode: 'DP-519672',
        passengerName: 'Priya Sharma',
        passengerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
        rating: 5,
        date: 'Today, 11:42 AM',
        comment: 'Outstanding pilot! Arrived in under 3 minutes with a clean sanitized helmet. Navigated the Indiranagar traffic smoothly and reached 10 minutes early.',
        tags: ['Clean Helmet', 'Prompt Pickup', 'Smooth Driving'],
      },
      {
        id: 'rev-102',
        tripCode: 'DP-488219',
        passengerName: 'Rahul Mehta',
        passengerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
        rating: 5,
        date: 'Yesterday, 6:15 PM',
        comment: 'Very polite behavior and safe riding habits. Did not over-speed even when the road was clear.',
        tags: ['Safe Riding', 'Polite Pilot'],
      },
      {
        id: 'rev-103',
        tripCode: 'DP-399104',
        passengerName: 'Sneha Reddy',
        passengerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
        rating: 4.8,
        date: '28 Sep 2026',
        comment: 'Great ride from Koramangala to HSR. Followed the optimal map route without asking unnecessary questions.',
        tags: ['Optimal Route', 'Great Communication'],
      },
      {
        id: 'rev-104',
        tripCode: 'DP-311028',
        passengerName: 'Karthik Rao',
        passengerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
        rating: 5,
        date: '25 Sep 2026',
        comment: 'Quick and reliable ride to the metro station. Highly recommended pilot for Bangalore commuters.',
        tags: ['Quick Transit', '5 Stars'],
      },
    ],
    tripHistory: [
      {
        id: 519672,
        bookingCode: 'DP-519672',
        status: 'COMPLETED',
        createdAt: '30 Sep 2026, 11:15 AM',
        pickupAddress: 'Vidhana Soudha, Dr. Ambedkar Veedhi, Bengaluru',
        dropAddress: 'Swami Vivekananda Road Metro Station, Indiranagar',
        distanceKm: 7.5,
        durationMins: 18,
        car: {
          make: 'Royal Enfield',
          model: 'Hunter 350 (Rapido Bike)',
          licensePlate: 'KA-05-BK-3344',
          category: 'BIKE',
          imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800',
        },
        passenger: {
          fullName: 'Priya Sharma',
          phoneNumber: '+91 98450 12345',
          email: 'customer@drivepulse.com',
          rating: 4.95,
        },
        pricing: {
          baseFare: 25.0,
          distanceFare: 52.5,
          platformFee: 7.5,
          taxes: 3.88,
          discount: 7.5,
          totalFare: 81.38,
        },
        paymentMethod: 'UPI / PhonePe',
        paymentStatus: 'SETTLED',
        otp: '5824',
        passengerReview: {
          rating: 5,
          comment: 'Outstanding pilot! Arrived in under 3 minutes with a clean sanitized helmet.',
        },
      },
      {
        id: 488219,
        bookingCode: 'DP-488219',
        status: 'COMPLETED',
        createdAt: '29 Sep 2026, 05:45 PM',
        pickupAddress: 'MG Road Metro Station, Bengaluru',
        dropAddress: 'Forum Mall, Koramangala 7th Block',
        distanceKm: 6.2,
        durationMins: 22,
        car: {
          make: 'Royal Enfield',
          model: 'Hunter 350 (Rapido Bike)',
          licensePlate: 'KA-05-BK-3344',
          category: 'BIKE',
          imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800',
        },
        passenger: {
          fullName: 'Rahul Mehta',
          phoneNumber: '+91 99123 44556',
          email: 'rahul.mehta@gmail.com',
          rating: 4.88,
        },
        pricing: {
          baseFare: 25.0,
          distanceFare: 43.4,
          platformFee: 6.5,
          taxes: 3.2,
          discount: 0.0,
          totalFare: 78.1,
        },
        paymentMethod: 'DrivePulse Cash',
        paymentStatus: 'SETTLED',
        otp: '9123',
        passengerReview: {
          rating: 5,
          comment: 'Very polite behavior and safe riding habits. Did not over-speed.',
        },
      },
      {
        id: 399104,
        bookingCode: 'DP-399104',
        status: 'COMPLETED',
        createdAt: '28 Sep 2026, 09:10 AM',
        pickupAddress: 'Indiranagar 100 Feet Road, Bengaluru',
        dropAddress: 'Bagmane Tech Park, CV Raman Nagar',
        distanceKm: 4.8,
        durationMins: 14,
        car: {
          make: 'Royal Enfield',
          model: 'Hunter 350 (Rapido Bike)',
          licensePlate: 'KA-05-BK-3344',
          category: 'BIKE',
          imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800',
        },
        passenger: {
          fullName: 'Sneha Reddy',
          phoneNumber: '+91 98860 77123',
          email: 'sneha.reddy@techcorp.in',
          rating: 4.92,
        },
        pricing: {
          baseFare: 25.0,
          distanceFare: 33.6,
          platformFee: 5.0,
          taxes: 2.6,
          discount: 5.0,
          totalFare: 61.2,
        },
        paymentMethod: 'Cash on Drop',
        paymentStatus: 'SETTLED',
        otp: '4412',
        passengerReview: {
          rating: 4.8,
          comment: 'Great ride from Koramangala to HSR. Followed the optimal map route.',
        },
      },
    ],
  },
  {
    id: 2,
    user: {
      fullName: 'Suresh Gowda',
      email: 'suresh@drivepulse.com',
      phoneNumber: '+91 98450 67890',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    },
    licenseNumber: 'KA-01-2018-0091823',
    vehicleAssigned: 'Tata Ace Gold Porter (KA-02-TC-7766)',
    category: 'TROLLEY_PORTER',
    experienceYears: 7,
    verificationStatus: 'APPROVED',
    rating: 4.87,
    totalTrips: 640,
    totalEarnings: 142800,
    completionRate: '98.5%',
    joinedDate: 'January 2021',
    reviews: [
      {
        id: 'rev-201',
        tripCode: 'DP-882103',
        passengerName: 'Anil Deshmukh',
        passengerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
        rating: 5,
        date: 'Yesterday, 3:20 PM',
        comment: 'Helped load and unload heavy furniture with great care. Arrived on time with proper tarpaulin cover.',
        tags: ['Careful Loading', 'Heavy Shifting', 'Punctual'],
      },
      {
        id: 'rev-202',
        tripCode: 'DP-761234',
        passengerName: 'Meera Nambiar',
        passengerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
        rating: 4.8,
        date: '26 Sep 2026',
        comment: 'Reliable porter service. Transparent upfront pricing without any bargaining at delivery.',
        tags: ['Upfront Pricing', 'Zero Hassle'],
      },
    ],
    tripHistory: [
      {
        id: 882103,
        bookingCode: 'DP-882103',
        status: 'COMPLETED',
        createdAt: '29 Sep 2026, 02:40 PM',
        pickupAddress: 'BTM Layout 2nd Stage, Bengaluru',
        dropAddress: 'Electronic City Phase 1, Near Infosys Gate',
        distanceKm: 14.2,
        durationMins: 42,
        car: {
          make: 'Tata',
          model: 'Ace Gold (Trolley / Porter)',
          licensePlate: 'KA-02-TC-7766',
          category: 'TROLLEY_PORTER',
          imageUrl: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800',
        },
        passenger: {
          fullName: 'Anil Deshmukh',
          phoneNumber: '+91 97401 22334',
          email: 'anil.deshmukh@outlook.com',
          rating: 4.8,
        },
        pricing: {
          baseFare: 180.0,
          distanceFare: 355.0,
          platformFee: 45.0,
          taxes: 28.5,
          discount: 25.0,
          totalFare: 583.5,
        },
        paymentMethod: 'UPI / GooglePay',
        paymentStatus: 'SETTLED',
        otp: '6719',
        passengerReview: {
          rating: 5,
          comment: 'Helped load and unload heavy furniture with great care. Arrived on time with proper tarpaulin cover.',
        },
      },
    ],
  },
  {
    id: 3,
    user: {
      fullName: 'Amit Verma',
      email: 'amit@drivepulse.com',
      phoneNumber: '+91 97123 99881',
      avatarUrl: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=150',
    },
    licenseNumber: 'KA-03-2022-0045129',
    vehicleAssigned: 'Bajaj RE CNG Auto (KA-03-TR-8811)',
    category: 'AUTO',
    experienceYears: 4,
    verificationStatus: 'APPROVED',
    rating: 4.88,
    totalTrips: 420,
    totalEarnings: 68400,
    completionRate: '99.0%',
    joinedDate: 'July 2023',
    reviews: [
      {
        id: 'rev-301',
        tripCode: 'DP-654921',
        passengerName: 'Deepa Krishnan',
        passengerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
        rating: 5,
        date: 'Today, 8:45 AM',
        comment: 'Cleanest auto I have travelled in! The driver turned on the digital meter immediately and did not cancel.',
        tags: ['Clean Vehicle', 'Meter Accuracy'],
      },
    ],
    tripHistory: [
      {
        id: 654921,
        bookingCode: 'DP-654921',
        status: 'COMPLETED',
        createdAt: '30 Sep 2026, 08:15 AM',
        pickupAddress: 'Jayanagar 4th Block, Bengaluru',
        dropAddress: 'Majestic Bus Stand, Bengaluru City Railway Station',
        distanceKm: 8.6,
        durationMins: 26,
        car: {
          make: 'Bajaj',
          model: 'RE Compact (CNG Auto)',
          licensePlate: 'KA-03-TR-8811',
          category: 'AUTO',
          imageUrl: 'https://images.unsplash.com/photo-1596706037526-7f41df0bb2f5?w=800',
        },
        passenger: {
          fullName: 'Deepa Krishnan',
          phoneNumber: '+91 99001 55667',
          email: 'deepa.k@gmail.com',
          rating: 4.9,
        },
        pricing: {
          baseFare: 45.0,
          distanceFare: 103.2,
          platformFee: 12.0,
          taxes: 7.8,
          discount: 10.0,
          totalFare: 158.0,
        },
        paymentMethod: 'UPI / PhonePe',
        paymentStatus: 'SETTLED',
        otp: '3187',
        passengerReview: {
          rating: 5,
          comment: 'Cleanest auto I have travelled in! The driver turned on the digital meter immediately.',
        },
      },
    ],
  },
];

